<?php

/**
 * @file
 * Contains webform_libraries.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_libraries_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_libraries module.
    case 'help.page.webform_libraries':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Webform libraries json') . '</p>';
      return $output;

    default:
  }
}
